Exit on null input for iprange

diff --git a/iprange b/iprange
--- a/iprange
+++ b/iprange
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# Using command substitution to return values from functions is slow
+# -- i.e. value=$(func) -- Global variables allow fast interaction
+# with functions, at the expense of namespace pollution and
+# hard-to-track program flow.
+
+# Converts a dotted-decimal IPv4 address representation to the 32 bit
+# number.
 function dot2ip {
   typeset dot=$1 ip
   typeset -a comps
@@ -14,6 +21,7 @@ function dot2ip {
   echo "$ip"
 }
 
+# Converts a 32 bit unsigned integer to dotted-decimal notation.
 function ip2dot {
   typeset ip=$1 w x y z
 
@@ -25,19 +33,34 @@ function ip2dot {
   echo "$w.$x.$y.$z"
 }
 
+# Generates a dotted-decimal representation of a network mask with N
+# bits high.
 function bits2mask {
   typeset bits=$1
 
   ip2dot "$(( (2**32 - 1) & ~(2**(32 - bits) - 1) ))"
 }
 
+# Masks an IPv4 address represented in dotted-decimal with a network
+# mask also represented in dotted-decimal.
+#
+# dotmask a.b.c.d m.n.o.p
+#
 function dotmask {
   typeset dot=$(dot2ip "$1") mask=$(dot2ip "$2")
 
   ip2dot "$((dot & mask))"
 }
 
+
+
+
+# Starting point
+# --------------
+
 network=$1
+
+[[ $network ]] || exit 1
 
 IFS=/ read -r network bits <<< "$network"
 
